[project]
name = "agfl"
version = "0.1.0"
description = "testing layer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch==2.2.2",
    "wfdb==4.3.1",
    "numpy==2.4.4",
    "matplotlib==3.10.8",
    "scikit-learn==1.8.0",
    "scipy==1.17.1",
    "tqdm==4.67.1",
    "umap-learn==0.5.11",
    "mne==1.12.1",
]
